version: '3'
services:
  tools:
    image: land007/theia:latest
    container_name: tools
    volumes:
      - kotbis-content:/home/project:cached
    ports:
      - "9229:9229"
      - "15050:5050"
    environment:
      - username=kotbis
      - password=fcea920f7412b5da7be0cf42b8c93759
    stdin_open: true
    tty: true

  web1:
    image: kotbis/kotbis-ap:1.4
    volumes:
      - kotbis-content:/var/www/localhost/htdocs
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  web2:
    image: kotbis/kotbis-ap:1.4
    volumes:
      - kotbis-content:/var/www/localhost/htdocs
    ports:
      - "8200:80"
    stdin_open: true
    tty: true
  web3:
    image: kotbis/kotbis-ap:1.4
    volumes:
      - kotbis-content:/var/www/localhost/htdocs
    ports:
      - "8300:80"
    stdin_open: true
    tty: true
  web4:
    image: kotbis/kotbis-ap:1.4
    volumes:
      - kotbis-content:/var/www/localhost/htdocs
    ports:
      - "8400:80"
    stdin_open: true
    tty: true
  web5:
    image: kotbis/kotbis-ap:1.4
    volumes:
      - kotbis-content:/var/www/localhost/htdocs
    ports:
      - "8500:80"
    stdin_open: true
    tty: true


volumes:
  kotbis-content:
    driver: local
